"""
Django settings for webui4VadCLIP project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from utils.weblink import get_ethernet_ip
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR_COMPARENT = Path(__file__).parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#-d4^#tkz)rmq)+1f*q2&ss!kil(yq8-e)90!t8y!fmua9%cz2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    "webuicore",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webui4VadCLIP.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webui4VadCLIP.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "vadclip_db",
        "USER": "mysql_admin",
        "PASSWORD": "661120",
        "HOST": "localhost",
        "PORT": "3306",
        "ATOMIC_REQUEST": False,
        "OPTIONS": {}
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "templates/static", ]
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
SOURCEVIDEOS_ROOT = os.path.join(BASE_DIR, 'media', 'SourceVideos')
# 定义第二个媒体目录（例如系统生成的文件）
SYSTEM_MEDIA_URL = 'data/'
SYSTEM_MEDIA_ROOT = os.path.join(BASE_DIR, 'data')  # 系统生成文件目录

AUTH_USER_MODEL = 'webuicore.User'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# OSGEO_VENV = BASE_DIR / 'venv/Lib/site-packages/osgeo/'
# GEOS_LIBRARY_PATH = str(OSGEO_VENV / 'geos_c.dll') 
# GDAL_LIBRARY_PATH = str(OSGEO_VENV / 'gdal310.dll')
# GEOS_LIBRARY_PATH = 'C:\\Users\\Admin\\.conda\\envs\\vadclip\\Lib\\site-packages\\osgeo\\geos_c.dll'
# GDAL_LIBRARY_PATH = 'C:\\Users\\Admin\\.conda\\envs\\vadclip\\Lib\\site-packages\\osgeo\\gdal.dll'
# os.environ["PATH"]+= os.pathsep +str(OSGEO_VENV)
# Define the server URL for the web UI
SERVER_URL = rf'http://{get_ethernet_ip("未知适配器")}:8000'
